### ISSUE TITLE
UI Improvements For The Colorblind

### ISSUE THREAD

**Issue by RnDMonkey** [LancelotP/satisfactory-map#17]
**Is your feature request related to a problem? Please describe.**
As a colorblind person, I cannot tell different icons apart by color alone.

**Describe the solution you'd like**
Adding a single character like "C" for coal and "O" for oil, etc, even if they overlap with things like caterium and coal (because these also have drastically different colors), would let me identify nodes readily.

**Describe alternatives you've considered**
The only real alternative I can come up with is to hide all nodes except the type of interest, but this makes it difficult to look for clusters of interested things at once while being able to discern them.

**Comment by S4XXX** [comment]
We plan to improve UI design, especially for color-blind users.

The first version available on https://satisfactory-map.lancelot.dev/ will remain active as long as these changes are not deployed on https://www.satisfactorymap.com

Thanks for your feedbacks

**Comment by LancelotP** [comment]
The first version has been closed as the new one provides the same visuals in terms of markers and accessibility.

Closing for now, feel free to reopen if the current state does not suit you.
