### ISSUE TITLE
Garbage nodes

### ISSUE THREAD

**Issue by angramainyu74** [LancelotP/satisfactory-map#21]
There's a ton of not real nodes on the map now.  This map was an invaluable resource before, but with so much bad data it's pretty much useless now.

**Comment by LancelotP** [comment]
Hey there ! Are you using this url https://www.satisfactorymap.com/ ?

That's the new one and the node à source from the game files. Please let me know if you still have "garbage" on this one and this so please provide a more constructive feedback.

Cheers.

**Comment by angramainyu74** [comment]
Heya Lancelot,

I was looking at https://satisfactory-map.lancelot.dev/ , which had a much
of extra nodes show up on that aren't in the game.

https://www.satisfactorymap.com/  appears to work great, though! Thanks!

**Comment by LancelotP** [comment]
Thanks for you reply :).

Hope you'll enjoy it !

Closing
