### ISSUE TITLE
URL sharing, filter configuration 0 is broken

### ISSUE THREAD

**Issue by S4XXX** [LancelotP/satisfactory-map#22]
**Describe the bug**
With URL sharing, the filter case '0' is problematic. Visual filters are in default configuration (839)

**To Reproduce**
#123;123;2;0

**Expected behavior**
No filter should be active

**Comment by LancelotP** [comment]
Fix should be release tonight hopefully.

**Comment by S4XXX** [comment]
Fixed and released
