### ISSUE TITLE
Add option for old icons

### ISSUE THREAD

**Issue by Xearoxde** [LancelotP/satisfactory-map#25]
Would you like to add an option to change the icons?

I don't really like the new icons.

Thank you =)

**Comment by LancelotP** [comment]
Hi, there's a colorblind option at the bottom of the menu that toggles the old icons, can you tell me if it's ok for you?

**Comment by Xearoxde** [comment]
That was really a fast answer ... I was on the way to close this tab.

Yeah, the "Color Blind" option helps a lot. It should be renamed ;-)

Thank You very much =)

**Comment by LancelotP** [comment]
Gonna close this, for now. We have a UI redesign in progress to help highlight this feature :)!
