### ISSUE TITLE
Update artifact icons to match visual style of the other map icons

### ISSUE THREAD

**Issue by bro15047** [LancelotP/satisfactory-map#27]
Instead of using images of the Somersloop and Mercer Sphere for icons some custom icons should be created to better match the style of the rest of the map markers.

I am by no means a professional, but here is an example for the Somersloop I whipped up real quick.
![somersloop_icon](https://user-images.githubusercontent.com/32497422/55913182-3d6e1e80-5ba1-11e9-82c7-6242f0040743.png)

**Comment by digitallymarked** [comment]
Hi,

Thanks for the feedback! We are working on the next batch of icons for the map which includes Somersloops, Mercer spheres and geysers amongst other things. We needed to launch with something that’s why we opted for the in game images :)

**Comment by LancelotP** [comment]
@bro15047 New icons just made it to staging can you tell me what do you think of those: https://staging.satisfactorymap.com/#199140.0390625;65223.4375;7;808976398 ?

**Comment by bro15047** [comment]
Looks good, that somersloop is a difficult one to mock up for sure.
