### ISSUE TITLE
Use Save file as actual/additional data source for a map

### ISSUE THREAD

**Issue by atehxx** [LancelotP/satisfactory-map#29]
You could check this code: [https://github.com/Goz3rr/SatisfactorySaveEditor](https://github.com/Goz3rr/SatisfactorySaveEditor), there is a C# library for loading game's Save file. Shouldn't be hard to convert it into JS and use here as a data source.

It's pretty easy to get from there locations of resources (and info if those are used, built on), or objects like Slugs or Drop pods, along with info if those are taken/used or not yet.
This would greatly improve the map usability - Could instantly see not only where I am, but also where are stuff I didn't take yet.

**Comment by S4XXX** [comment]
Hi ! We already know this repo :)
We have our own file parser with more advanced functionality than the Goz3r parser, such as being able to recover all the collected objects, to associate EPIC ids to each player in the save, to recognize the host among these players etc (j have already contacted Goz3r a few days ago for collected items)

You should check are roadmap on trello : https://trello.com/b/Pz8tj1OX/roadmap-for-satisfactory-map

**Comment by atehxx** [comment]
Oh I checked here only, alright then, keep up the good work! :)

**Comment by S4XXX** [comment]
Thank you :) Closed
