### ISSUE TITLE
Locate me does not work with save files from the publicly released Experimental build

### ISSUE THREAD

**Issue by petestrash** [LancelotP/satisfactory-map#33]
The Locate me feature does not work with save files from the publicly released Experimental build.

**Comment by S4XXX** [comment]
Hello @petestrash !
The locate me feature from experimental version save file is already fixed. Sadly @LancelotP is now on vacation and can't released it on prod server.

**Comment by petestrash** [comment]
Thanks for that. 

I tried the staging server also, should it work there?

**Comment by S4XXX** [comment]
I can't release it on staging too :/ These are servers owned by @LancelotP and I do not have access yet.

But in fact it should work on some cases if you upload a save either created from the experimental build or updated by the experimental build.

let me explain, it works if none of the following rules are used:

- some nodes locations changed or some are deleted but miners on top of them don't. these miners don't properly link to a node in the save file and the locate me feature crashed.
- new nodes have been created, miners on top of them are properly linked in the save file but we can't find the real nodes in our data and a crash occurs.

**Comment by petestrash** [comment]
Ok thanks.  Great work, I appreciate it.

**Comment by cbknutson** [comment]
Any word on when a push to the public page will happen?

**Comment by petestrash** [comment]
Still no luck with saves from either of the last 2 major experimental builds.  

Is anyone using other methods to track which pods we have opened?

**Comment by petestrash** [comment]
Just letting you know the locate me feature is now working for me again.
