### ISSUE TITLE
Browser refresh doesn’t maintain scale

### ISSUE THREAD

**Issue by 7Rickus** [LancelotP/satisfactory-map#38]
First of all, thank you guys for an awesome tool.

The issue I'd like to raise is that a browser refresh rememberers you’re preferences except for the “Icon Size” option. 

Every time I revisit the site, I need to reset Icon Size back to the lowest setting. It’d be nice if this could be remembered between sessions.

**Comment by LancelotP** [comment]
@7Rickus Thanks for raising this, I'll try to come up with a solution. Would this be OK if the size is not stored in the URL? Would be easier to store it inside local storage instead of messing around with the binary mask in the url

**Comment by 7Rickus** [comment]
Apologies, I’d imagine you were already using local storage. That would be ideal.

Cheers,
Rick

**Comment by LancelotP** [comment]
@7Rickus fixed and deployed ;)
